version: "3.7"


networks:
  public:
    name: public-net
    driver: bridge
  secure:
    name: secure-net
    driver: bridge

services:
  eureka-service:
    image: eureka-service:0.1.0
    ports:
      - "8761:8761"
    networks:
      - secure
      - public


  email-service:
    image: email:0.1.0
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_MAIL_HOST: mailhog
    networks:
      - secure
    depends_on:
      - kafka
      - mailhog
      - eureka-service

  subscription-service:
    image: subscription:0.1.0
    ports:
      - "8080:8080"
    networks:
      - secure
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - kafka
      - eureka-service

  public-service:
    image: public:0.1.0
    networks:
      - public
      - secure
    ports:
      - "8083:8083"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    networks:
      - secure
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    networks:
      - secure
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    networks:
      - secure
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:9092,DOCKER_EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:9092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    networks:
      - secure
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - "kafka"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - secure