server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

topic:
  name: t.newsletter.createSubscription

spring:
  application:
    name: subscription-service
  jpa:
    hibernate.ddl-auto: update
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: compose-postgres
    password: compose-postgres
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      properties:
        spring.json.type.mapping: 'eventSubscription:com.adidas.test.subscription.domain.Subscription'
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

